project_id = "memsytfgkmdotevwssqm"

[functions.ai-feedback]
verify_jwt = false

[functions.sign-upload]
verify_jwt = false

[functions.capture-lead]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

