import { FC } from 'react';
import {
  Gavel,
  Scissors,
  Building2,
  Heart,
  Camera,
  PenTool,
  Brush,
  Video,
  Palette,
  Calculator,
  Briefcase,
  Shield,
  Zap,
  Clock,
  Star,
  Users,
  MapPin,
  Award,
  BookOpen,
  Calendar,
  Phone,
  MessageSquare,
  HandHeart,
  Store,
  Utensils,
  Hammer,
  Wrench,
  Home,
  TrendingUp,
  BarChart3,
  DollarSign,
  CheckCircle2,
  Globe,
} from 'lucide-react';

const iconMap = {
  gavel: Gavel,
  scissors: Scissors,
  building2: Building2,
  heart: Heart,
  camera: Camera,
  'pen-tool': PenTool,
  brush: Brush,
  video: Video,
  palette: Palette,
  calculator: Calculator,
  briefcase: Briefcase,
  shield: Shield,
  zap: Zap,
  clock: Clock,
  star: Star,
  users: Users,
  'map-pin': MapPin,
  award: Award,
  'book-open': BookOpen,
  calendar: Calendar,
  phone: Phone,
  'message-square': MessageSquare,
  'hand-heart': HandHeart,
  store: Store,
  utensils: Utensils,
  hammer: Hammer,
  wrench: Wrench,
  home: Home,
  'trending-up': TrendingUp,
  'bar-chart-3': BarChart3,
  'dollar-sign': DollarSign,
  'check-circle-2': CheckCircle2,
  globe: Globe,
} as const;

export const IndustryIcon: FC<{ name?: string; className?: string }> = ({ name, className }) => {
  const Icon = name && iconMap[name as keyof typeof iconMap] ? iconMap[name as keyof typeof iconMap] : Briefcase;
  return <Icon className={className} />;
};
