// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://memsytfgkmdotevwssqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lbXN5dGZna21kb3Rldndzc3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MTYzMzUsImV4cCI6MjA3MDM5MjMzNX0.WaUX5DkLLRu3PfVpPnNuJnNIUx6TD-89rpB5xOb5eR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});