name: Scheduled Deploy
on:
  schedule:
    # Run every 8 hours
    - cron: '0 */8 * * *'
  workflow_dispatch: # Allow manual trigger
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Vercel Deploy
      run: |
        curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
    
    - name: Log deployment trigger
      run: |
        echo "Deployment hook triggered at $(date)"
